[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_SUPABASE_URL = "https://mxfyfjirrqwkwuwswosv.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "${REACT_APP_SUPABASE_ANON_KEY}"
  REACT_APP_API_URL = "https://trackmyjobs-api.onrender.com/api"
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://trackmyjobs-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200