services:
  - type: web
    name: trackmyjobs-api
    runtime: node
    repo: https://github.com/Khalipha-Samela/TrackMyJobs.git
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://track-myjobs.netlify.app
      - key: DB_HOST
        fromDatabase:
          name: trackmyjobs-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: trackmyjobs-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: trackmyjobs-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: trackmyjobs-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: trackmyjobs-db
          property: database

databases:
  - name: trackmyjobs-db
    databaseName: trackmyjobs
    user: trackmyjobs_user
    plan: free