services:
  - type: web
    name: trackmyjobs-api
    runtime: node
    repo: https://github.com/Khalipha-Samela/TrackMyJobs
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://track-myjobs.netlify.app
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false