services:
  - type: web
    name: trackmyjobs-api
    runtime: node
    repo: https://github.com/Khalipha-Samela/TrackMyJobs.git
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: trackmyjobs-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: trackmyjobs-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: trackmyjobs-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: trackmyjobs-db
          property: database
      - key: DB_PORT
        value: 5432

databases:
  - name: trackmyjobs-db
    databaseName: trackmyjobs
    user: trackmyjobs_user
    plan: free